using Oscar

include("structs/tropical_pluecker_vector.jl")
include("structs/dual_cell.jl")
include("structs/mixed_cell.jl")
include("structs/mixed_path.jl")
include("structs/mixed_cell_cone.jl")
include("structs/dual_path.jl")
include("routines/generate_support.jl")
include("routines/stable_intersection_point.jl")
include("routines/compute_drift.jl")
include("routines/cayley_embedding.jl")
include("routines/next_breaking_point.jl")
# include("cayley_embedding.jl")
# include("structs/mixed_cell_cone.jl")
# include("routines/ray_intersects_cone.jl")
